# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Minify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.4.3
    # Runs a single command using the runners shell
    - run: ls
    - name: Run a one-line script
      run: |
        npx terser ./js/init.js ./js/malla.js ./js/ramo.js -c -m -o ./js/min1.js
        npx terser ./js/init.js ./js/malla.js ./js/ramo.js ./js/selectableRamo.js ./js/semesterManager.js ./js/priorix.js ./js/mallaEditor.js -c -m -o ./js/min2.js
        npx terser ./js/init.js ./js/malla.js ./js/ramo.js ./js/selectableRamo.js ./js/semesterManager.js ./js/generator.js ./js/mallaEditor.js -c -m -o ./js/min3.js
        npx terser ./js/init.js ./js/malla.js ./js/ramo.js ./js/customMalla.js -c -m -o ./js/min4.js 
    - name: Commit Changes
      uses: EndBug/add-and-commit@v4
      with:
        message: "Minified .js files"
        add: "*"
        author_name: "Github Action"
        author_email: "action@github.com"
      env:
      # This is necessary in order to push a commit to the repo
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
      # Runs a set of commands using the runners shell
